// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseData12.proto

package com.common.netty.protobuf;

public final class BaseData12 {
  private BaseData12() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface A212OrBuilder extends
      // @@protoc_insertion_point(interface_extends:A212)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    boolean hasParkingId();
    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    int getParkingId();

    /**
     * <pre>
     *停车流水
     * </pre>
     *
     * <code>required string parkingSerial = 2;</code>
     */
    boolean hasParkingSerial();
    /**
     * <pre>
     *停车流水
     * </pre>
     *
     * <code>required string parkingSerial = 2;</code>
     */
    String getParkingSerial();
    /**
     * <pre>
     *停车流水
     * </pre>
     *
     * <code>required string parkingSerial = 2;</code>
     */
    com.google.protobuf.ByteString
        getParkingSerialBytes();

    /**
     * <pre>
     *减免时长(分钟)
     * </pre>
     *
     * <code>required int32 freeTime = 3;</code>
     */
    boolean hasFreeTime();
    /**
     * <pre>
     *减免时长(分钟)
     * </pre>
     *
     * <code>required int32 freeTime = 3;</code>
     */
    int getFreeTime();

    /**
     * <pre>
     *截止时间(yyyyMMddHHmmss)
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    boolean hasEndTime();
    /**
     * <pre>
     *截止时间(yyyyMMddHHmmss)
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    String getEndTime();
    /**
     * <pre>
     *截止时间(yyyyMMddHHmmss)
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();
  }
  /**
   * <pre>
   *核心业务指令-查询停车费指令-请求对象
   * </pre>
   *
   * Protobuf type {@code A212}
   */
  public  static final class A212 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:A212)
      A212OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use A212.newBuilder() to construct.
    private A212(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private A212() {
      parkingId_ = 0;
      parkingSerial_ = "";
      freeTime_ = 0;
      endTime_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private A212(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              parkingId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              parkingSerial_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              freeTime_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              endTime_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseData12.internal_static_A212_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseData12.internal_static_A212_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              A212.class, Builder.class);
    }

    private int bitField0_;
    public static final int PARKINGID_FIELD_NUMBER = 1;
    private int parkingId_;
    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    public boolean hasParkingId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    public int getParkingId() {
      return parkingId_;
    }

    public static final int PARKINGSERIAL_FIELD_NUMBER = 2;
    private volatile Object parkingSerial_;
    /**
     * <pre>
     *停车流水
     * </pre>
     *
     * <code>required string parkingSerial = 2;</code>
     */
    public boolean hasParkingSerial() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *停车流水
     * </pre>
     *
     * <code>required string parkingSerial = 2;</code>
     */
    public String getParkingSerial() {
      Object ref = parkingSerial_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parkingSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *停车流水
     * </pre>
     *
     * <code>required string parkingSerial = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParkingSerialBytes() {
      Object ref = parkingSerial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        parkingSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FREETIME_FIELD_NUMBER = 3;
    private int freeTime_;
    /**
     * <pre>
     *减免时长(分钟)
     * </pre>
     *
     * <code>required int32 freeTime = 3;</code>
     */
    public boolean hasFreeTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *减免时长(分钟)
     * </pre>
     *
     * <code>required int32 freeTime = 3;</code>
     */
    public int getFreeTime() {
      return freeTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 4;
    private volatile Object endTime_;
    /**
     * <pre>
     *截止时间(yyyyMMddHHmmss)
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *截止时间(yyyyMMddHHmmss)
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    public String getEndTime() {
      Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *截止时间(yyyyMMddHHmmss)
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasParkingId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParkingSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFreeTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, parkingId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parkingSerial_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, freeTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, parkingId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, parkingSerial_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, freeTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof A212)) {
        return super.equals(obj);
      }
      A212 other = (A212) obj;

      boolean result = true;
      result = result && (hasParkingId() == other.hasParkingId());
      if (hasParkingId()) {
        result = result && (getParkingId()
            == other.getParkingId());
      }
      result = result && (hasParkingSerial() == other.hasParkingSerial());
      if (hasParkingSerial()) {
        result = result && getParkingSerial()
            .equals(other.getParkingSerial());
      }
      result = result && (hasFreeTime() == other.hasFreeTime());
      if (hasFreeTime()) {
        result = result && (getFreeTime()
            == other.getFreeTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && getEndTime()
            .equals(other.getEndTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParkingId()) {
        hash = (37 * hash) + PARKINGID_FIELD_NUMBER;
        hash = (53 * hash) + getParkingId();
      }
      if (hasParkingSerial()) {
        hash = (37 * hash) + PARKINGSERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getParkingSerial().hashCode();
      }
      if (hasFreeTime()) {
        hash = (37 * hash) + FREETIME_FIELD_NUMBER;
        hash = (53 * hash) + getFreeTime();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static A212 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A212 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A212 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A212 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A212 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A212 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A212 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A212 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static A212 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static A212 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static A212 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A212 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(A212 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *核心业务指令-查询停车费指令-请求对象
     * </pre>
     *
     * Protobuf type {@code A212}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:A212)
        A212OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseData12.internal_static_A212_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseData12.internal_static_A212_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                A212.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.BaseData12.A212.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        parkingId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        parkingSerial_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        freeTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseData12.internal_static_A212_descriptor;
      }

      public A212 getDefaultInstanceForType() {
        return A212.getDefaultInstance();
      }

      public A212 build() {
        A212 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public A212 buildPartial() {
        A212 result = new A212(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.parkingId_ = parkingId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parkingSerial_ = parkingSerial_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.freeTime_ = freeTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof A212) {
          return mergeFrom((A212)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(A212 other) {
        if (other == A212.getDefaultInstance()) return this;
        if (other.hasParkingId()) {
          setParkingId(other.getParkingId());
        }
        if (other.hasParkingSerial()) {
          bitField0_ |= 0x00000002;
          parkingSerial_ = other.parkingSerial_;
          onChanged();
        }
        if (other.hasFreeTime()) {
          setFreeTime(other.getFreeTime());
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000008;
          endTime_ = other.endTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasParkingId()) {
          return false;
        }
        if (!hasParkingSerial()) {
          return false;
        }
        if (!hasFreeTime()) {
          return false;
        }
        if (!hasEndTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        A212 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (A212) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int parkingId_ ;
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public boolean hasParkingId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public int getParkingId() {
        return parkingId_;
      }
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public Builder setParkingId(int value) {
        bitField0_ |= 0x00000001;
        parkingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public Builder clearParkingId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        parkingId_ = 0;
        onChanged();
        return this;
      }

      private Object parkingSerial_ = "";
      /**
       * <pre>
       *停车流水
       * </pre>
       *
       * <code>required string parkingSerial = 2;</code>
       */
      public boolean hasParkingSerial() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *停车流水
       * </pre>
       *
       * <code>required string parkingSerial = 2;</code>
       */
      public String getParkingSerial() {
        Object ref = parkingSerial_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parkingSerial_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *停车流水
       * </pre>
       *
       * <code>required string parkingSerial = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParkingSerialBytes() {
        Object ref = parkingSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          parkingSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *停车流水
       * </pre>
       *
       * <code>required string parkingSerial = 2;</code>
       */
      public Builder setParkingSerial(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parkingSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车流水
       * </pre>
       *
       * <code>required string parkingSerial = 2;</code>
       */
      public Builder clearParkingSerial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parkingSerial_ = getDefaultInstance().getParkingSerial();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车流水
       * </pre>
       *
       * <code>required string parkingSerial = 2;</code>
       */
      public Builder setParkingSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parkingSerial_ = value;
        onChanged();
        return this;
      }

      private int freeTime_ ;
      /**
       * <pre>
       *减免时长(分钟)
       * </pre>
       *
       * <code>required int32 freeTime = 3;</code>
       */
      public boolean hasFreeTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *减免时长(分钟)
       * </pre>
       *
       * <code>required int32 freeTime = 3;</code>
       */
      public int getFreeTime() {
        return freeTime_;
      }
      /**
       * <pre>
       *减免时长(分钟)
       * </pre>
       *
       * <code>required int32 freeTime = 3;</code>
       */
      public Builder setFreeTime(int value) {
        bitField0_ |= 0x00000004;
        freeTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *减免时长(分钟)
       * </pre>
       *
       * <code>required int32 freeTime = 3;</code>
       */
      public Builder clearFreeTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        freeTime_ = 0;
        onChanged();
        return this;
      }

      private Object endTime_ = "";
      /**
       * <pre>
       *截止时间(yyyyMMddHHmmss)
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *截止时间(yyyyMMddHHmmss)
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public String getEndTime() {
        Object ref = endTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            endTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *截止时间(yyyyMMddHHmmss)
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *截止时间(yyyyMMddHHmmss)
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public Builder setEndTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *截止时间(yyyyMMddHHmmss)
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *截止时间(yyyyMMddHHmmss)
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:A212)
    }

    // @@protoc_insertion_point(class_scope:A212)
    private static final A212 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new A212();
    }

    public static A212 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<A212>
        PARSER = new com.google.protobuf.AbstractParser<A212>() {
      public A212 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new A212(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<A212> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<A212> getParserForType() {
      return PARSER;
    }

    public A212 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface B212OrBuilder extends
      // @@protoc_insertion_point(interface_extends:B212)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *状态值
     * </pre>
     *
     * <code>required int32 status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <pre>
     *状态值
     * </pre>
     *
     * <code>required int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    boolean hasClientSerial();
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    String getClientSerial();
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientSerialBytes();

    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string startTime = 3;</code>
     */
    boolean hasStartTime();
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string startTime = 3;</code>
     */
    String getStartTime();
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string startTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <pre>
     *出场时间
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    boolean hasEndTime();
    /**
     * <pre>
     *出场时间
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    String getEndTime();
    /**
     * <pre>
     *出场时间
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    /**
     * <pre>
     *停车费 分
     * </pre>
     *
     * <code>required int32 fee = 5;</code>
     */
    boolean hasFee();
    /**
     * <pre>
     *停车费 分
     * </pre>
     *
     * <code>required int32 fee = 5;</code>
     */
    int getFee();
  }
  /**
   * <pre>
   *核心业务指令-查询停车费指令-应答对象
   * </pre>
   *
   * Protobuf type {@code B212}
   */
  public  static final class B212 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:B212)
      B212OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use B212.newBuilder() to construct.
    private B212(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private B212() {
      status_ = 0;
      clientSerial_ = "";
      startTime_ = "";
      endTime_ = "";
      fee_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private B212(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              clientSerial_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              startTime_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              endTime_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              fee_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseData12.internal_static_B212_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseData12.internal_static_B212_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              B212.class, Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <pre>
     *状态值
     * </pre>
     *
     * <code>required int32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *状态值
     * </pre>
     *
     * <code>required int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int CLIENTSERIAL_FIELD_NUMBER = 2;
    private volatile Object clientSerial_;
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    public boolean hasClientSerial() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    public String getClientSerial() {
      Object ref = clientSerial_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientSerialBytes() {
      Object ref = clientSerial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 3;
    private volatile Object startTime_;
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string startTime = 3;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string startTime = 3;</code>
     */
    public String getStartTime() {
      Object ref = startTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startTime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string startTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDTIME_FIELD_NUMBER = 4;
    private volatile Object endTime_;
    /**
     * <pre>
     *出场时间
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *出场时间
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    public String getEndTime() {
      Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *出场时间
     * </pre>
     *
     * <code>required string endTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEE_FIELD_NUMBER = 5;
    private int fee_;
    /**
     * <pre>
     *停车费 分
     * </pre>
     *
     * <code>required int32 fee = 5;</code>
     */
    public boolean hasFee() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *停车费 分
     * </pre>
     *
     * <code>required int32 fee = 5;</code>
     */
    public int getFee() {
      return fee_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientSerial_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, fee_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientSerial_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, startTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, fee_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof B212)) {
        return super.equals(obj);
      }
      B212 other = (B212) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && (getStatus()
            == other.getStatus());
      }
      result = result && (hasClientSerial() == other.hasClientSerial());
      if (hasClientSerial()) {
        result = result && getClientSerial()
            .equals(other.getClientSerial());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && getStartTime()
            .equals(other.getStartTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && getEndTime()
            .equals(other.getEndTime());
      }
      result = result && (hasFee() == other.hasFee());
      if (hasFee()) {
        result = result && (getFee()
            == other.getFee());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasClientSerial()) {
        hash = (37 * hash) + CLIENTSERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getClientSerial().hashCode();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime().hashCode();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      if (hasFee()) {
        hash = (37 * hash) + FEE_FIELD_NUMBER;
        hash = (53 * hash) + getFee();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static B212 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B212 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B212 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B212 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B212 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B212 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B212 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static B212 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static B212 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static B212 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static B212 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static B212 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(B212 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *核心业务指令-查询停车费指令-应答对象
     * </pre>
     *
     * Protobuf type {@code B212}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:B212)
        B212OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseData12.internal_static_B212_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseData12.internal_static_B212_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                B212.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.BaseData12.B212.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSerial_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        fee_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseData12.internal_static_B212_descriptor;
      }

      public B212 getDefaultInstanceForType() {
        return B212.getDefaultInstance();
      }

      public B212 build() {
        B212 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public B212 buildPartial() {
        B212 result = new B212(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientSerial_ = clientSerial_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fee_ = fee_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof B212) {
          return mergeFrom((B212)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(B212 other) {
        if (other == B212.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasClientSerial()) {
          bitField0_ |= 0x00000002;
          clientSerial_ = other.clientSerial_;
          onChanged();
        }
        if (other.hasStartTime()) {
          bitField0_ |= 0x00000004;
          startTime_ = other.startTime_;
          onChanged();
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000008;
          endTime_ = other.endTime_;
          onChanged();
        }
        if (other.hasFee()) {
          setFee(other.getFee());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        if (!hasClientSerial()) {
          return false;
        }
        if (!hasStartTime()) {
          return false;
        }
        if (!hasEndTime()) {
          return false;
        }
        if (!hasFee()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        B212 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (B212) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <pre>
       *状态值
       * </pre>
       *
       * <code>required int32 status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *状态值
       * </pre>
       *
       * <code>required int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       *状态值
       * </pre>
       *
       * <code>required int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *状态值
       * </pre>
       *
       * <code>required int32 status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private Object clientSerial_ = "";
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public boolean hasClientSerial() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public String getClientSerial() {
        Object ref = clientSerial_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSerial_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientSerialBytes() {
        Object ref = clientSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public Builder setClientSerial(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public Builder clearClientSerial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSerial_ = getDefaultInstance().getClientSerial();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public Builder setClientSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSerial_ = value;
        onChanged();
        return this;
      }

      private Object startTime_ = "";
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string startTime = 3;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string startTime = 3;</code>
       */
      public String getStartTime() {
        Object ref = startTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            startTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string startTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string startTime = 3;</code>
       */
      public Builder setStartTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string startTime = 3;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string startTime = 3;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        startTime_ = value;
        onChanged();
        return this;
      }

      private Object endTime_ = "";
      /**
       * <pre>
       *出场时间
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *出场时间
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public String getEndTime() {
        Object ref = endTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            endTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *出场时间
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *出场时间
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public Builder setEndTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *出场时间
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *出场时间
       * </pre>
       *
       * <code>required string endTime = 4;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }

      private int fee_ ;
      /**
       * <pre>
       *停车费 分
       * </pre>
       *
       * <code>required int32 fee = 5;</code>
       */
      public boolean hasFee() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *停车费 分
       * </pre>
       *
       * <code>required int32 fee = 5;</code>
       */
      public int getFee() {
        return fee_;
      }
      /**
       * <pre>
       *停车费 分
       * </pre>
       *
       * <code>required int32 fee = 5;</code>
       */
      public Builder setFee(int value) {
        bitField0_ |= 0x00000010;
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车费 分
       * </pre>
       *
       * <code>required int32 fee = 5;</code>
       */
      public Builder clearFee() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fee_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:B212)
    }

    // @@protoc_insertion_point(class_scope:B212)
    private static final B212 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new B212();
    }

    public static B212 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<B212>
        PARSER = new com.google.protobuf.AbstractParser<B212>() {
      public B212 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new B212(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<B212> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<B212> getParserForType() {
      return PARSER;
    }

    public B212 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_A212_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_A212_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_B212_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_B212_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020BaseData12.proto\"S\n\004A212\022\021\n\tparkingId\030" +
      "\001 \002(\005\022\025\n\rparkingSerial\030\002 \002(\t\022\020\n\010freeTime" +
      "\030\003 \002(\005\022\017\n\007endTime\030\004 \002(\t\"]\n\004B212\022\016\n\006statu" +
      "s\030\001 \002(\005\022\024\n\014clientSerial\030\002 \002(\t\022\021\n\tstartTi" +
      "me\030\003 \002(\t\022\017\n\007endTime\030\004 \002(\t\022\013\n\003fee\030\005 \002(\005B\'" +
      "\n\031com.common.model.protobufB\nBaseData12"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_A212_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_A212_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_A212_descriptor,
        new String[] { "ParkingId", "ParkingSerial", "FreeTime", "EndTime", });
    internal_static_B212_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_B212_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_B212_descriptor,
        new String[] { "Status", "ClientSerial", "StartTime", "EndTime", "Fee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
