// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseData17.proto

package com.common.netty.protobuf;

public final class BaseData17 {
  private BaseData17() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface A217OrBuilder extends
      // @@protoc_insertion_point(interface_extends:A217)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 1;</code>
     */
    boolean hasWayNo();
    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 1;</code>
     */
    int getWayNo();

    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    boolean hasParkingId();
    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    int getParkingId();
  }
  /**
   * <pre>
   *核心业务指令-查询出口车辆信息指令-请求对象
   * </pre>
   *
   * Protobuf type {@code A217}
   */
  public  static final class A217 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:A217)
      A217OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use A217.newBuilder() to construct.
    private A217(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private A217() {
      wayNo_ = 0;
      parkingId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private A217(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              wayNo_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              parkingId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseData17.internal_static_A217_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseData17.internal_static_A217_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              A217.class, Builder.class);
    }

    private int bitField0_;
    public static final int WAYNO_FIELD_NUMBER = 1;
    private int wayNo_;
    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 1;</code>
     */
    public boolean hasWayNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 1;</code>
     */
    public int getWayNo() {
      return wayNo_;
    }

    public static final int PARKINGID_FIELD_NUMBER = 2;
    private int parkingId_;
    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    public boolean hasParkingId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    public int getParkingId() {
      return parkingId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWayNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParkingId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, wayNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, parkingId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, wayNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, parkingId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof A217)) {
        return super.equals(obj);
      }
      A217 other = (A217) obj;

      boolean result = true;
      result = result && (hasWayNo() == other.hasWayNo());
      if (hasWayNo()) {
        result = result && (getWayNo()
            == other.getWayNo());
      }
      result = result && (hasParkingId() == other.hasParkingId());
      if (hasParkingId()) {
        result = result && (getParkingId()
            == other.getParkingId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWayNo()) {
        hash = (37 * hash) + WAYNO_FIELD_NUMBER;
        hash = (53 * hash) + getWayNo();
      }
      if (hasParkingId()) {
        hash = (37 * hash) + PARKINGID_FIELD_NUMBER;
        hash = (53 * hash) + getParkingId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static A217 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A217 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A217 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A217 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A217 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A217 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A217 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A217 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static A217 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static A217 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static A217 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A217 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(A217 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *核心业务指令-查询出口车辆信息指令-请求对象
     * </pre>
     *
     * Protobuf type {@code A217}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:A217)
        A217OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseData17.internal_static_A217_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseData17.internal_static_A217_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                A217.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.BaseData17.A217.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        wayNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        parkingId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseData17.internal_static_A217_descriptor;
      }

      public A217 getDefaultInstanceForType() {
        return A217.getDefaultInstance();
      }

      public A217 build() {
        A217 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public A217 buildPartial() {
        A217 result = new A217(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.wayNo_ = wayNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parkingId_ = parkingId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof A217) {
          return mergeFrom((A217)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(A217 other) {
        if (other == A217.getDefaultInstance()) return this;
        if (other.hasWayNo()) {
          setWayNo(other.getWayNo());
        }
        if (other.hasParkingId()) {
          setParkingId(other.getParkingId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWayNo()) {
          return false;
        }
        if (!hasParkingId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        A217 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (A217) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int wayNo_ ;
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 1;</code>
       */
      public boolean hasWayNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 1;</code>
       */
      public int getWayNo() {
        return wayNo_;
      }
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 1;</code>
       */
      public Builder setWayNo(int value) {
        bitField0_ |= 0x00000001;
        wayNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 1;</code>
       */
      public Builder clearWayNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wayNo_ = 0;
        onChanged();
        return this;
      }

      private int parkingId_ ;
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public boolean hasParkingId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public int getParkingId() {
        return parkingId_;
      }
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public Builder setParkingId(int value) {
        bitField0_ |= 0x00000002;
        parkingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public Builder clearParkingId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parkingId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:A217)
    }

    // @@protoc_insertion_point(class_scope:A217)
    private static final A217 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new A217();
    }

    public static A217 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<A217>
        PARSER = new com.google.protobuf.AbstractParser<A217>() {
      public A217 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new A217(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<A217> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<A217> getParserForType() {
      return PARSER;
    }

    public A217 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface B217OrBuilder extends
      // @@protoc_insertion_point(interface_extends:B217)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 1;</code>
     */
    boolean hasClientSerial();
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 1;</code>
     */
    String getClientSerial();
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientSerialBytes();

    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    boolean hasParkingId();
    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    int getParkingId();

    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string inTime = 3;</code>
     */
    boolean hasInTime();
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string inTime = 3;</code>
     */
    String getInTime();
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string inTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getInTimeBytes();

    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 4;</code>
     */
    boolean hasWayNo();
    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 4;</code>
     */
    int getWayNo();

    /**
     * <pre>
     *通道名称长度
     * </pre>
     *
     * <code>required int32 wayNameLen = 5;</code>
     */
    boolean hasWayNameLen();
    /**
     * <pre>
     *通道名称长度
     * </pre>
     *
     * <code>required int32 wayNameLen = 5;</code>
     */
    int getWayNameLen();

    /**
     * <pre>
     *通道名称
     * </pre>
     *
     * <code>required string wayName = 6;</code>
     */
    boolean hasWayName();
    /**
     * <pre>
     *通道名称
     * </pre>
     *
     * <code>required string wayName = 6;</code>
     */
    String getWayName();
    /**
     * <pre>
     *通道名称
     * </pre>
     *
     * <code>required string wayName = 6;</code>
     */
    com.google.protobuf.ByteString
        getWayNameBytes();

    /**
     * <pre>
     *总停车费
     * </pre>
     *
     * <code>required int32 parkingFeeTotal = 7;</code>
     */
    boolean hasParkingFeeTotal();
    /**
     * <pre>
     *总停车费
     * </pre>
     *
     * <code>required int32 parkingFeeTotal = 7;</code>
     */
    int getParkingFeeTotal();

    /**
     * <pre>
     *已交次数
     * </pre>
     *
     * <code>required int32 hasPayCount = 8;</code>
     */
    boolean hasHasPayCount();
    /**
     * <pre>
     *已交次数
     * </pre>
     *
     * <code>required int32 hasPayCount = 8;</code>
     */
    int getHasPayCount();

    /**
     * <pre>
     *已交金额
     * </pre>
     *
     * <code>required int32 hasPayFee = 9;</code>
     */
    boolean hasHasPayFee();
    /**
     * <pre>
     *已交金额
     * </pre>
     *
     * <code>required int32 hasPayFee = 9;</code>
     */
    int getHasPayFee();

    /**
     * <pre>
     *结算时间
     * </pre>
     *
     * <code>required string endTime = 10;</code>
     */
    boolean hasEndTime();
    /**
     * <pre>
     *结算时间
     * </pre>
     *
     * <code>required string endTime = 10;</code>
     */
    String getEndTime();
    /**
     * <pre>
     *结算时间
     * </pre>
     *
     * <code>required string endTime = 10;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();
  }
  /**
   * <pre>
   *核心业务指令-查询出口车辆信息指令-应答对象
   * </pre>
   *
   * Protobuf type {@code B217}
   */
  public  static final class B217 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:B217)
      B217OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use B217.newBuilder() to construct.
    private B217(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private B217() {
      clientSerial_ = "";
      parkingId_ = 0;
      inTime_ = "";
      wayNo_ = 0;
      wayNameLen_ = 0;
      wayName_ = "";
      parkingFeeTotal_ = 0;
      hasPayCount_ = 0;
      hasPayFee_ = 0;
      endTime_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private B217(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              clientSerial_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              parkingId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              inTime_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              wayNo_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              wayNameLen_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              wayName_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              parkingFeeTotal_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              hasPayCount_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              hasPayFee_ = input.readInt32();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              endTime_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseData17.internal_static_B217_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseData17.internal_static_B217_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              B217.class, Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTSERIAL_FIELD_NUMBER = 1;
    private volatile Object clientSerial_;
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 1;</code>
     */
    public boolean hasClientSerial() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 1;</code>
     */
    public String getClientSerial() {
      Object ref = clientSerial_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientSerialBytes() {
      Object ref = clientSerial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARKINGID_FIELD_NUMBER = 2;
    private int parkingId_;
    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    public boolean hasParkingId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *停车场编号
     * </pre>
     *
     * <code>required int32 parkingId = 2;</code>
     */
    public int getParkingId() {
      return parkingId_;
    }

    public static final int INTIME_FIELD_NUMBER = 3;
    private volatile Object inTime_;
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string inTime = 3;</code>
     */
    public boolean hasInTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string inTime = 3;</code>
     */
    public String getInTime() {
      Object ref = inTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          inTime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *入场时间
     * </pre>
     *
     * <code>required string inTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInTimeBytes() {
      Object ref = inTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        inTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WAYNO_FIELD_NUMBER = 4;
    private int wayNo_;
    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 4;</code>
     */
    public boolean hasWayNo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *通道编号
     * </pre>
     *
     * <code>required int32 wayNo = 4;</code>
     */
    public int getWayNo() {
      return wayNo_;
    }

    public static final int WAYNAMELEN_FIELD_NUMBER = 5;
    private int wayNameLen_;
    /**
     * <pre>
     *通道名称长度
     * </pre>
     *
     * <code>required int32 wayNameLen = 5;</code>
     */
    public boolean hasWayNameLen() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *通道名称长度
     * </pre>
     *
     * <code>required int32 wayNameLen = 5;</code>
     */
    public int getWayNameLen() {
      return wayNameLen_;
    }

    public static final int WAYNAME_FIELD_NUMBER = 6;
    private volatile Object wayName_;
    /**
     * <pre>
     *通道名称
     * </pre>
     *
     * <code>required string wayName = 6;</code>
     */
    public boolean hasWayName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *通道名称
     * </pre>
     *
     * <code>required string wayName = 6;</code>
     */
    public String getWayName() {
      Object ref = wayName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wayName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *通道名称
     * </pre>
     *
     * <code>required string wayName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWayNameBytes() {
      Object ref = wayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        wayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARKINGFEETOTAL_FIELD_NUMBER = 7;
    private int parkingFeeTotal_;
    /**
     * <pre>
     *总停车费
     * </pre>
     *
     * <code>required int32 parkingFeeTotal = 7;</code>
     */
    public boolean hasParkingFeeTotal() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *总停车费
     * </pre>
     *
     * <code>required int32 parkingFeeTotal = 7;</code>
     */
    public int getParkingFeeTotal() {
      return parkingFeeTotal_;
    }

    public static final int HASPAYCOUNT_FIELD_NUMBER = 8;
    private int hasPayCount_;
    /**
     * <pre>
     *已交次数
     * </pre>
     *
     * <code>required int32 hasPayCount = 8;</code>
     */
    public boolean hasHasPayCount() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     *已交次数
     * </pre>
     *
     * <code>required int32 hasPayCount = 8;</code>
     */
    public int getHasPayCount() {
      return hasPayCount_;
    }

    public static final int HASPAYFEE_FIELD_NUMBER = 9;
    private int hasPayFee_;
    /**
     * <pre>
     *已交金额
     * </pre>
     *
     * <code>required int32 hasPayFee = 9;</code>
     */
    public boolean hasHasPayFee() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *已交金额
     * </pre>
     *
     * <code>required int32 hasPayFee = 9;</code>
     */
    public int getHasPayFee() {
      return hasPayFee_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 10;
    private volatile Object endTime_;
    /**
     * <pre>
     *结算时间
     * </pre>
     *
     * <code>required string endTime = 10;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     *结算时间
     * </pre>
     *
     * <code>required string endTime = 10;</code>
     */
    public String getEndTime() {
      Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *结算时间
     * </pre>
     *
     * <code>required string endTime = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClientSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParkingId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWayNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWayNameLen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWayName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParkingFeeTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasPayCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasPayFee()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientSerial_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, parkingId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, inTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, wayNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, wayNameLen_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, wayName_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, parkingFeeTotal_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, hasPayCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, hasPayFee_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, endTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientSerial_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, parkingId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, inTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, wayNo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, wayNameLen_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, wayName_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, parkingFeeTotal_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, hasPayCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, hasPayFee_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof B217)) {
        return super.equals(obj);
      }
      B217 other = (B217) obj;

      boolean result = true;
      result = result && (hasClientSerial() == other.hasClientSerial());
      if (hasClientSerial()) {
        result = result && getClientSerial()
            .equals(other.getClientSerial());
      }
      result = result && (hasParkingId() == other.hasParkingId());
      if (hasParkingId()) {
        result = result && (getParkingId()
            == other.getParkingId());
      }
      result = result && (hasInTime() == other.hasInTime());
      if (hasInTime()) {
        result = result && getInTime()
            .equals(other.getInTime());
      }
      result = result && (hasWayNo() == other.hasWayNo());
      if (hasWayNo()) {
        result = result && (getWayNo()
            == other.getWayNo());
      }
      result = result && (hasWayNameLen() == other.hasWayNameLen());
      if (hasWayNameLen()) {
        result = result && (getWayNameLen()
            == other.getWayNameLen());
      }
      result = result && (hasWayName() == other.hasWayName());
      if (hasWayName()) {
        result = result && getWayName()
            .equals(other.getWayName());
      }
      result = result && (hasParkingFeeTotal() == other.hasParkingFeeTotal());
      if (hasParkingFeeTotal()) {
        result = result && (getParkingFeeTotal()
            == other.getParkingFeeTotal());
      }
      result = result && (hasHasPayCount() == other.hasHasPayCount());
      if (hasHasPayCount()) {
        result = result && (getHasPayCount()
            == other.getHasPayCount());
      }
      result = result && (hasHasPayFee() == other.hasHasPayFee());
      if (hasHasPayFee()) {
        result = result && (getHasPayFee()
            == other.getHasPayFee());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && getEndTime()
            .equals(other.getEndTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClientSerial()) {
        hash = (37 * hash) + CLIENTSERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getClientSerial().hashCode();
      }
      if (hasParkingId()) {
        hash = (37 * hash) + PARKINGID_FIELD_NUMBER;
        hash = (53 * hash) + getParkingId();
      }
      if (hasInTime()) {
        hash = (37 * hash) + INTIME_FIELD_NUMBER;
        hash = (53 * hash) + getInTime().hashCode();
      }
      if (hasWayNo()) {
        hash = (37 * hash) + WAYNO_FIELD_NUMBER;
        hash = (53 * hash) + getWayNo();
      }
      if (hasWayNameLen()) {
        hash = (37 * hash) + WAYNAMELEN_FIELD_NUMBER;
        hash = (53 * hash) + getWayNameLen();
      }
      if (hasWayName()) {
        hash = (37 * hash) + WAYNAME_FIELD_NUMBER;
        hash = (53 * hash) + getWayName().hashCode();
      }
      if (hasParkingFeeTotal()) {
        hash = (37 * hash) + PARKINGFEETOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getParkingFeeTotal();
      }
      if (hasHasPayCount()) {
        hash = (37 * hash) + HASPAYCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getHasPayCount();
      }
      if (hasHasPayFee()) {
        hash = (37 * hash) + HASPAYFEE_FIELD_NUMBER;
        hash = (53 * hash) + getHasPayFee();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static B217 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B217 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B217 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B217 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B217 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B217 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B217 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static B217 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static B217 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static B217 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static B217 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static B217 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(B217 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *核心业务指令-查询出口车辆信息指令-应答对象
     * </pre>
     *
     * Protobuf type {@code B217}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:B217)
        B217OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseData17.internal_static_B217_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseData17.internal_static_B217_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                B217.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.BaseData17.B217.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientSerial_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        parkingId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        inTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        wayNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        wayNameLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        wayName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        parkingFeeTotal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        hasPayCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        hasPayFee_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseData17.internal_static_B217_descriptor;
      }

      public B217 getDefaultInstanceForType() {
        return B217.getDefaultInstance();
      }

      public B217 build() {
        B217 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public B217 buildPartial() {
        B217 result = new B217(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientSerial_ = clientSerial_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parkingId_ = parkingId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.inTime_ = inTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.wayNo_ = wayNo_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.wayNameLen_ = wayNameLen_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.wayName_ = wayName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.parkingFeeTotal_ = parkingFeeTotal_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.hasPayCount_ = hasPayCount_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.hasPayFee_ = hasPayFee_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof B217) {
          return mergeFrom((B217)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(B217 other) {
        if (other == B217.getDefaultInstance()) return this;
        if (other.hasClientSerial()) {
          bitField0_ |= 0x00000001;
          clientSerial_ = other.clientSerial_;
          onChanged();
        }
        if (other.hasParkingId()) {
          setParkingId(other.getParkingId());
        }
        if (other.hasInTime()) {
          bitField0_ |= 0x00000004;
          inTime_ = other.inTime_;
          onChanged();
        }
        if (other.hasWayNo()) {
          setWayNo(other.getWayNo());
        }
        if (other.hasWayNameLen()) {
          setWayNameLen(other.getWayNameLen());
        }
        if (other.hasWayName()) {
          bitField0_ |= 0x00000020;
          wayName_ = other.wayName_;
          onChanged();
        }
        if (other.hasParkingFeeTotal()) {
          setParkingFeeTotal(other.getParkingFeeTotal());
        }
        if (other.hasHasPayCount()) {
          setHasPayCount(other.getHasPayCount());
        }
        if (other.hasHasPayFee()) {
          setHasPayFee(other.getHasPayFee());
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000200;
          endTime_ = other.endTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientSerial()) {
          return false;
        }
        if (!hasParkingId()) {
          return false;
        }
        if (!hasInTime()) {
          return false;
        }
        if (!hasWayNo()) {
          return false;
        }
        if (!hasWayNameLen()) {
          return false;
        }
        if (!hasWayName()) {
          return false;
        }
        if (!hasParkingFeeTotal()) {
          return false;
        }
        if (!hasHasPayCount()) {
          return false;
        }
        if (!hasHasPayFee()) {
          return false;
        }
        if (!hasEndTime()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        B217 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (B217) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object clientSerial_ = "";
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 1;</code>
       */
      public boolean hasClientSerial() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 1;</code>
       */
      public String getClientSerial() {
        Object ref = clientSerial_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSerial_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientSerialBytes() {
        Object ref = clientSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 1;</code>
       */
      public Builder setClientSerial(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 1;</code>
       */
      public Builder clearClientSerial() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSerial_ = getDefaultInstance().getClientSerial();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 1;</code>
       */
      public Builder setClientSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientSerial_ = value;
        onChanged();
        return this;
      }

      private int parkingId_ ;
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public boolean hasParkingId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public int getParkingId() {
        return parkingId_;
      }
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public Builder setParkingId(int value) {
        bitField0_ |= 0x00000002;
        parkingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车场编号
       * </pre>
       *
       * <code>required int32 parkingId = 2;</code>
       */
      public Builder clearParkingId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parkingId_ = 0;
        onChanged();
        return this;
      }

      private Object inTime_ = "";
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string inTime = 3;</code>
       */
      public boolean hasInTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string inTime = 3;</code>
       */
      public String getInTime() {
        Object ref = inTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            inTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string inTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInTimeBytes() {
        Object ref = inTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          inTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string inTime = 3;</code>
       */
      public Builder setInTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        inTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string inTime = 3;</code>
       */
      public Builder clearInTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        inTime_ = getDefaultInstance().getInTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *入场时间
       * </pre>
       *
       * <code>required string inTime = 3;</code>
       */
      public Builder setInTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        inTime_ = value;
        onChanged();
        return this;
      }

      private int wayNo_ ;
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 4;</code>
       */
      public boolean hasWayNo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 4;</code>
       */
      public int getWayNo() {
        return wayNo_;
      }
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 4;</code>
       */
      public Builder setWayNo(int value) {
        bitField0_ |= 0x00000008;
        wayNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通道编号
       * </pre>
       *
       * <code>required int32 wayNo = 4;</code>
       */
      public Builder clearWayNo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        wayNo_ = 0;
        onChanged();
        return this;
      }

      private int wayNameLen_ ;
      /**
       * <pre>
       *通道名称长度
       * </pre>
       *
       * <code>required int32 wayNameLen = 5;</code>
       */
      public boolean hasWayNameLen() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *通道名称长度
       * </pre>
       *
       * <code>required int32 wayNameLen = 5;</code>
       */
      public int getWayNameLen() {
        return wayNameLen_;
      }
      /**
       * <pre>
       *通道名称长度
       * </pre>
       *
       * <code>required int32 wayNameLen = 5;</code>
       */
      public Builder setWayNameLen(int value) {
        bitField0_ |= 0x00000010;
        wayNameLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通道名称长度
       * </pre>
       *
       * <code>required int32 wayNameLen = 5;</code>
       */
      public Builder clearWayNameLen() {
        bitField0_ = (bitField0_ & ~0x00000010);
        wayNameLen_ = 0;
        onChanged();
        return this;
      }

      private Object wayName_ = "";
      /**
       * <pre>
       *通道名称
       * </pre>
       *
       * <code>required string wayName = 6;</code>
       */
      public boolean hasWayName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *通道名称
       * </pre>
       *
       * <code>required string wayName = 6;</code>
       */
      public String getWayName() {
        Object ref = wayName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            wayName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *通道名称
       * </pre>
       *
       * <code>required string wayName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWayNameBytes() {
        Object ref = wayName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          wayName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *通道名称
       * </pre>
       *
       * <code>required string wayName = 6;</code>
       */
      public Builder setWayName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        wayName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通道名称
       * </pre>
       *
       * <code>required string wayName = 6;</code>
       */
      public Builder clearWayName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        wayName_ = getDefaultInstance().getWayName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通道名称
       * </pre>
       *
       * <code>required string wayName = 6;</code>
       */
      public Builder setWayNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        wayName_ = value;
        onChanged();
        return this;
      }

      private int parkingFeeTotal_ ;
      /**
       * <pre>
       *总停车费
       * </pre>
       *
       * <code>required int32 parkingFeeTotal = 7;</code>
       */
      public boolean hasParkingFeeTotal() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *总停车费
       * </pre>
       *
       * <code>required int32 parkingFeeTotal = 7;</code>
       */
      public int getParkingFeeTotal() {
        return parkingFeeTotal_;
      }
      /**
       * <pre>
       *总停车费
       * </pre>
       *
       * <code>required int32 parkingFeeTotal = 7;</code>
       */
      public Builder setParkingFeeTotal(int value) {
        bitField0_ |= 0x00000040;
        parkingFeeTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总停车费
       * </pre>
       *
       * <code>required int32 parkingFeeTotal = 7;</code>
       */
      public Builder clearParkingFeeTotal() {
        bitField0_ = (bitField0_ & ~0x00000040);
        parkingFeeTotal_ = 0;
        onChanged();
        return this;
      }

      private int hasPayCount_ ;
      /**
       * <pre>
       *已交次数
       * </pre>
       *
       * <code>required int32 hasPayCount = 8;</code>
       */
      public boolean hasHasPayCount() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *已交次数
       * </pre>
       *
       * <code>required int32 hasPayCount = 8;</code>
       */
      public int getHasPayCount() {
        return hasPayCount_;
      }
      /**
       * <pre>
       *已交次数
       * </pre>
       *
       * <code>required int32 hasPayCount = 8;</code>
       */
      public Builder setHasPayCount(int value) {
        bitField0_ |= 0x00000080;
        hasPayCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已交次数
       * </pre>
       *
       * <code>required int32 hasPayCount = 8;</code>
       */
      public Builder clearHasPayCount() {
        bitField0_ = (bitField0_ & ~0x00000080);
        hasPayCount_ = 0;
        onChanged();
        return this;
      }

      private int hasPayFee_ ;
      /**
       * <pre>
       *已交金额
       * </pre>
       *
       * <code>required int32 hasPayFee = 9;</code>
       */
      public boolean hasHasPayFee() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *已交金额
       * </pre>
       *
       * <code>required int32 hasPayFee = 9;</code>
       */
      public int getHasPayFee() {
        return hasPayFee_;
      }
      /**
       * <pre>
       *已交金额
       * </pre>
       *
       * <code>required int32 hasPayFee = 9;</code>
       */
      public Builder setHasPayFee(int value) {
        bitField0_ |= 0x00000100;
        hasPayFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已交金额
       * </pre>
       *
       * <code>required int32 hasPayFee = 9;</code>
       */
      public Builder clearHasPayFee() {
        bitField0_ = (bitField0_ & ~0x00000100);
        hasPayFee_ = 0;
        onChanged();
        return this;
      }

      private Object endTime_ = "";
      /**
       * <pre>
       *结算时间
       * </pre>
       *
       * <code>required string endTime = 10;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       *结算时间
       * </pre>
       *
       * <code>required string endTime = 10;</code>
       */
      public String getEndTime() {
        Object ref = endTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            endTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *结算时间
       * </pre>
       *
       * <code>required string endTime = 10;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *结算时间
       * </pre>
       *
       * <code>required string endTime = 10;</code>
       */
      public Builder setEndTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结算时间
       * </pre>
       *
       * <code>required string endTime = 10;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结算时间
       * </pre>
       *
       * <code>required string endTime = 10;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        endTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:B217)
    }

    // @@protoc_insertion_point(class_scope:B217)
    private static final B217 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new B217();
    }

    public static B217 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<B217>
        PARSER = new com.google.protobuf.AbstractParser<B217>() {
      public B217 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new B217(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<B217> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<B217> getParserForType() {
      return PARSER;
    }

    public B217 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_A217_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_A217_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_B217_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_B217_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020BaseData17.proto\"(\n\004A217\022\r\n\005wayNo\030\001 \002(" +
      "\005\022\021\n\tparkingId\030\002 \002(\005\"\305\001\n\004B217\022\024\n\014clientS" +
      "erial\030\001 \002(\t\022\021\n\tparkingId\030\002 \002(\005\022\016\n\006inTime" +
      "\030\003 \002(\t\022\r\n\005wayNo\030\004 \002(\005\022\022\n\nwayNameLen\030\005 \002(" +
      "\005\022\017\n\007wayName\030\006 \002(\t\022\027\n\017parkingFeeTotal\030\007 " +
      "\002(\005\022\023\n\013hasPayCount\030\010 \002(\005\022\021\n\thasPayFee\030\t " +
      "\002(\005\022\017\n\007endTime\030\n \002(\tB\'\n\031com.common.model" +
      ".protobufB\nBaseData17"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_A217_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_A217_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_A217_descriptor,
        new String[] { "WayNo", "ParkingId", });
    internal_static_B217_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_B217_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_B217_descriptor,
        new String[] { "ClientSerial", "ParkingId", "InTime", "WayNo", "WayNameLen", "WayName", "ParkingFeeTotal", "HasPayCount", "HasPayFee", "EndTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
