// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseData14.proto

package com.common.netty.protobuf;

public final class BaseData14 {
  private BaseData14() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface A114OrBuilder extends
      // @@protoc_insertion_point(interface_extends:A114)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    boolean hasParkingId();
    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    int getParkingId();

    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    boolean hasClientSerial();
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    String getClientSerial();
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientSerialBytes();
  }
  /**
   * <pre>
   *核心业务指令-查询支付状态指令-请求对象
   * </pre>
   *
   * Protobuf type {@code A114}
   */
  public  static final class A114 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:A114)
      A114OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use A114.newBuilder() to construct.
    private A114(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private A114() {
      parkingId_ = 0;
      clientSerial_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private A114(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              parkingId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              clientSerial_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseData14.internal_static_A114_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseData14.internal_static_A114_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              A114.class, Builder.class);
    }

    private int bitField0_;
    public static final int PARKINGID_FIELD_NUMBER = 1;
    private int parkingId_;
    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    public boolean hasParkingId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *停车场id
     * </pre>
     *
     * <code>required int32 parkingId = 1;</code>
     */
    public int getParkingId() {
      return parkingId_;
    }

    public static final int CLIENTSERIAL_FIELD_NUMBER = 2;
    private volatile Object clientSerial_;
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    public boolean hasClientSerial() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    public String getClientSerial() {
      Object ref = clientSerial_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *进场流水号
     * </pre>
     *
     * <code>required string clientSerial = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientSerialBytes() {
      Object ref = clientSerial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasParkingId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, parkingId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientSerial_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, parkingId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientSerial_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof A114)) {
        return super.equals(obj);
      }
      A114 other = (A114) obj;

      boolean result = true;
      result = result && (hasParkingId() == other.hasParkingId());
      if (hasParkingId()) {
        result = result && (getParkingId()
            == other.getParkingId());
      }
      result = result && (hasClientSerial() == other.hasClientSerial());
      if (hasClientSerial()) {
        result = result && getClientSerial()
            .equals(other.getClientSerial());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParkingId()) {
        hash = (37 * hash) + PARKINGID_FIELD_NUMBER;
        hash = (53 * hash) + getParkingId();
      }
      if (hasClientSerial()) {
        hash = (37 * hash) + CLIENTSERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getClientSerial().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static A114 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A114 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A114 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A114 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A114 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static A114 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static A114 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A114 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static A114 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static A114 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static A114 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static A114 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(A114 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *核心业务指令-查询支付状态指令-请求对象
     * </pre>
     *
     * Protobuf type {@code A114}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:A114)
        A114OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseData14.internal_static_A114_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseData14.internal_static_A114_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                A114.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.BaseData14.A114.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        parkingId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSerial_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseData14.internal_static_A114_descriptor;
      }

      public A114 getDefaultInstanceForType() {
        return A114.getDefaultInstance();
      }

      public A114 build() {
        A114 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public A114 buildPartial() {
        A114 result = new A114(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.parkingId_ = parkingId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientSerial_ = clientSerial_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof A114) {
          return mergeFrom((A114)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(A114 other) {
        if (other == A114.getDefaultInstance()) return this;
        if (other.hasParkingId()) {
          setParkingId(other.getParkingId());
        }
        if (other.hasClientSerial()) {
          bitField0_ |= 0x00000002;
          clientSerial_ = other.clientSerial_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasParkingId()) {
          return false;
        }
        if (!hasClientSerial()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        A114 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (A114) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int parkingId_ ;
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public boolean hasParkingId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public int getParkingId() {
        return parkingId_;
      }
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public Builder setParkingId(int value) {
        bitField0_ |= 0x00000001;
        parkingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车场id
       * </pre>
       *
       * <code>required int32 parkingId = 1;</code>
       */
      public Builder clearParkingId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        parkingId_ = 0;
        onChanged();
        return this;
      }

      private Object clientSerial_ = "";
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public boolean hasClientSerial() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public String getClientSerial() {
        Object ref = clientSerial_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientSerial_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientSerialBytes() {
        Object ref = clientSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public Builder setClientSerial(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public Builder clearClientSerial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSerial_ = getDefaultInstance().getClientSerial();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *进场流水号
       * </pre>
       *
       * <code>required string clientSerial = 2;</code>
       */
      public Builder setClientSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientSerial_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:A114)
    }

    // @@protoc_insertion_point(class_scope:A114)
    private static final A114 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new A114();
    }

    public static A114 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<A114>
        PARSER = new com.google.protobuf.AbstractParser<A114>() {
      public A114 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new A114(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<A114> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<A114> getParserForType() {
      return PARSER;
    }

    public A114 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface B114OrBuilder extends
      // @@protoc_insertion_point(interface_extends:B114)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *累计支付次数
     * </pre>
     *
     * <code>required int32 payCount = 1;</code>
     */
    boolean hasPayCount();
    /**
     * <pre>
     *累计支付次数
     * </pre>
     *
     * <code>required int32 payCount = 1;</code>
     */
    int getPayCount();

    /**
     * <pre>
     *累计支付总金额
     * </pre>
     *
     * <code>required int32 paySum = 2;</code>
     */
    boolean hasPaySum();
    /**
     * <pre>
     *累计支付总金额
     * </pre>
     *
     * <code>required int32 paySum = 2;</code>
     */
    int getPaySum();

    /**
     * <pre>
     *线上累计支付次数
     * </pre>
     *
     * <code>required int32 onLinePaycCount = 3;</code>
     */
    boolean hasOnLinePaycCount();
    /**
     * <pre>
     *线上累计支付次数
     * </pre>
     *
     * <code>required int32 onLinePaycCount = 3;</code>
     */
    int getOnLinePaycCount();

    /**
     * <pre>
     *线上累计支付总金额
     * </pre>
     *
     * <code>required int32 onLinePaySum = 4;</code>
     */
    boolean hasOnLinePaySum();
    /**
     * <pre>
     *线上累计支付总金额
     * </pre>
     *
     * <code>required int32 onLinePaySum = 4;</code>
     */
    int getOnLinePaySum();

    /**
     * <pre>
     *线下累计支付次数
     * </pre>
     *
     * <code>required int32 offLinePaycCount = 5;</code>
     */
    boolean hasOffLinePaycCount();
    /**
     * <pre>
     *线下累计支付次数
     * </pre>
     *
     * <code>required int32 offLinePaycCount = 5;</code>
     */
    int getOffLinePaycCount();

    /**
     * <pre>
     *线下累计支付总金额
     * </pre>
     *
     * <code>required int32 offLinePaySum = 6;</code>
     */
    boolean hasOffLinePaySum();
    /**
     * <pre>
     *线下累计支付总金额
     * </pre>
     *
     * <code>required int32 offLinePaySum = 6;</code>
     */
    int getOffLinePaySum();

    /**
     * <pre>
     *结算截止时间
     * </pre>
     *
     * <code>optional string endTime = 7;</code>
     */
    boolean hasEndTime();
    /**
     * <pre>
     *结算截止时间
     * </pre>
     *
     * <code>optional string endTime = 7;</code>
     */
    String getEndTime();
    /**
     * <pre>
     *结算截止时间
     * </pre>
     *
     * <code>optional string endTime = 7;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();
  }
  /**
   * <pre>
   *核心业务指令-查询支付状态指令-应答对象
   * </pre>
   *
   * Protobuf type {@code B114}
   */
  public  static final class B114 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:B114)
      B114OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use B114.newBuilder() to construct.
    private B114(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private B114() {
      payCount_ = 0;
      paySum_ = 0;
      onLinePaycCount_ = 0;
      onLinePaySum_ = 0;
      offLinePaycCount_ = 0;
      offLinePaySum_ = 0;
      endTime_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private B114(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              payCount_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              paySum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              onLinePaycCount_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              onLinePaySum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              offLinePaycCount_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              offLinePaySum_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              endTime_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseData14.internal_static_B114_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseData14.internal_static_B114_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              B114.class, Builder.class);
    }

    private int bitField0_;
    public static final int PAYCOUNT_FIELD_NUMBER = 1;
    private int payCount_;
    /**
     * <pre>
     *累计支付次数
     * </pre>
     *
     * <code>required int32 payCount = 1;</code>
     */
    public boolean hasPayCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *累计支付次数
     * </pre>
     *
     * <code>required int32 payCount = 1;</code>
     */
    public int getPayCount() {
      return payCount_;
    }

    public static final int PAYSUM_FIELD_NUMBER = 2;
    private int paySum_;
    /**
     * <pre>
     *累计支付总金额
     * </pre>
     *
     * <code>required int32 paySum = 2;</code>
     */
    public boolean hasPaySum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *累计支付总金额
     * </pre>
     *
     * <code>required int32 paySum = 2;</code>
     */
    public int getPaySum() {
      return paySum_;
    }

    public static final int ONLINEPAYCCOUNT_FIELD_NUMBER = 3;
    private int onLinePaycCount_;
    /**
     * <pre>
     *线上累计支付次数
     * </pre>
     *
     * <code>required int32 onLinePaycCount = 3;</code>
     */
    public boolean hasOnLinePaycCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *线上累计支付次数
     * </pre>
     *
     * <code>required int32 onLinePaycCount = 3;</code>
     */
    public int getOnLinePaycCount() {
      return onLinePaycCount_;
    }

    public static final int ONLINEPAYSUM_FIELD_NUMBER = 4;
    private int onLinePaySum_;
    /**
     * <pre>
     *线上累计支付总金额
     * </pre>
     *
     * <code>required int32 onLinePaySum = 4;</code>
     */
    public boolean hasOnLinePaySum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *线上累计支付总金额
     * </pre>
     *
     * <code>required int32 onLinePaySum = 4;</code>
     */
    public int getOnLinePaySum() {
      return onLinePaySum_;
    }

    public static final int OFFLINEPAYCCOUNT_FIELD_NUMBER = 5;
    private int offLinePaycCount_;
    /**
     * <pre>
     *线下累计支付次数
     * </pre>
     *
     * <code>required int32 offLinePaycCount = 5;</code>
     */
    public boolean hasOffLinePaycCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *线下累计支付次数
     * </pre>
     *
     * <code>required int32 offLinePaycCount = 5;</code>
     */
    public int getOffLinePaycCount() {
      return offLinePaycCount_;
    }

    public static final int OFFLINEPAYSUM_FIELD_NUMBER = 6;
    private int offLinePaySum_;
    /**
     * <pre>
     *线下累计支付总金额
     * </pre>
     *
     * <code>required int32 offLinePaySum = 6;</code>
     */
    public boolean hasOffLinePaySum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *线下累计支付总金额
     * </pre>
     *
     * <code>required int32 offLinePaySum = 6;</code>
     */
    public int getOffLinePaySum() {
      return offLinePaySum_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 7;
    private volatile Object endTime_;
    /**
     * <pre>
     *结算截止时间
     * </pre>
     *
     * <code>optional string endTime = 7;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *结算截止时间
     * </pre>
     *
     * <code>optional string endTime = 7;</code>
     */
    public String getEndTime() {
      Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endTime_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *结算截止时间
     * </pre>
     *
     * <code>optional string endTime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPayCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPaySum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOnLinePaycCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOnLinePaySum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffLinePaycCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffLinePaySum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, payCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, paySum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, onLinePaycCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, onLinePaySum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, offLinePaycCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, offLinePaySum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, endTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, payCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, paySum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, onLinePaycCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, onLinePaySum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, offLinePaycCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, offLinePaySum_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof B114)) {
        return super.equals(obj);
      }
      B114 other = (B114) obj;

      boolean result = true;
      result = result && (hasPayCount() == other.hasPayCount());
      if (hasPayCount()) {
        result = result && (getPayCount()
            == other.getPayCount());
      }
      result = result && (hasPaySum() == other.hasPaySum());
      if (hasPaySum()) {
        result = result && (getPaySum()
            == other.getPaySum());
      }
      result = result && (hasOnLinePaycCount() == other.hasOnLinePaycCount());
      if (hasOnLinePaycCount()) {
        result = result && (getOnLinePaycCount()
            == other.getOnLinePaycCount());
      }
      result = result && (hasOnLinePaySum() == other.hasOnLinePaySum());
      if (hasOnLinePaySum()) {
        result = result && (getOnLinePaySum()
            == other.getOnLinePaySum());
      }
      result = result && (hasOffLinePaycCount() == other.hasOffLinePaycCount());
      if (hasOffLinePaycCount()) {
        result = result && (getOffLinePaycCount()
            == other.getOffLinePaycCount());
      }
      result = result && (hasOffLinePaySum() == other.hasOffLinePaySum());
      if (hasOffLinePaySum()) {
        result = result && (getOffLinePaySum()
            == other.getOffLinePaySum());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && getEndTime()
            .equals(other.getEndTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPayCount()) {
        hash = (37 * hash) + PAYCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getPayCount();
      }
      if (hasPaySum()) {
        hash = (37 * hash) + PAYSUM_FIELD_NUMBER;
        hash = (53 * hash) + getPaySum();
      }
      if (hasOnLinePaycCount()) {
        hash = (37 * hash) + ONLINEPAYCCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getOnLinePaycCount();
      }
      if (hasOnLinePaySum()) {
        hash = (37 * hash) + ONLINEPAYSUM_FIELD_NUMBER;
        hash = (53 * hash) + getOnLinePaySum();
      }
      if (hasOffLinePaycCount()) {
        hash = (37 * hash) + OFFLINEPAYCCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getOffLinePaycCount();
      }
      if (hasOffLinePaySum()) {
        hash = (37 * hash) + OFFLINEPAYSUM_FIELD_NUMBER;
        hash = (53 * hash) + getOffLinePaySum();
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static B114 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B114 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B114 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B114 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B114 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static B114 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static B114 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static B114 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static B114 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static B114 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static B114 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static B114 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(B114 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *核心业务指令-查询支付状态指令-应答对象
     * </pre>
     *
     * Protobuf type {@code B114}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:B114)
        B114OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseData14.internal_static_B114_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseData14.internal_static_B114_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                B114.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.BaseData14.B114.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        payCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        paySum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        onLinePaycCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        onLinePaySum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        offLinePaycCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        offLinePaySum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseData14.internal_static_B114_descriptor;
      }

      public B114 getDefaultInstanceForType() {
        return B114.getDefaultInstance();
      }

      public B114 build() {
        B114 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public B114 buildPartial() {
        B114 result = new B114(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.payCount_ = payCount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.paySum_ = paySum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.onLinePaycCount_ = onLinePaycCount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.onLinePaySum_ = onLinePaySum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.offLinePaycCount_ = offLinePaycCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.offLinePaySum_ = offLinePaySum_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof B114) {
          return mergeFrom((B114)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(B114 other) {
        if (other == B114.getDefaultInstance()) return this;
        if (other.hasPayCount()) {
          setPayCount(other.getPayCount());
        }
        if (other.hasPaySum()) {
          setPaySum(other.getPaySum());
        }
        if (other.hasOnLinePaycCount()) {
          setOnLinePaycCount(other.getOnLinePaycCount());
        }
        if (other.hasOnLinePaySum()) {
          setOnLinePaySum(other.getOnLinePaySum());
        }
        if (other.hasOffLinePaycCount()) {
          setOffLinePaycCount(other.getOffLinePaycCount());
        }
        if (other.hasOffLinePaySum()) {
          setOffLinePaySum(other.getOffLinePaySum());
        }
        if (other.hasEndTime()) {
          bitField0_ |= 0x00000040;
          endTime_ = other.endTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPayCount()) {
          return false;
        }
        if (!hasPaySum()) {
          return false;
        }
        if (!hasOnLinePaycCount()) {
          return false;
        }
        if (!hasOnLinePaySum()) {
          return false;
        }
        if (!hasOffLinePaycCount()) {
          return false;
        }
        if (!hasOffLinePaySum()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        B114 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (B114) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int payCount_ ;
      /**
       * <pre>
       *累计支付次数
       * </pre>
       *
       * <code>required int32 payCount = 1;</code>
       */
      public boolean hasPayCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *累计支付次数
       * </pre>
       *
       * <code>required int32 payCount = 1;</code>
       */
      public int getPayCount() {
        return payCount_;
      }
      /**
       * <pre>
       *累计支付次数
       * </pre>
       *
       * <code>required int32 payCount = 1;</code>
       */
      public Builder setPayCount(int value) {
        bitField0_ |= 0x00000001;
        payCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *累计支付次数
       * </pre>
       *
       * <code>required int32 payCount = 1;</code>
       */
      public Builder clearPayCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        payCount_ = 0;
        onChanged();
        return this;
      }

      private int paySum_ ;
      /**
       * <pre>
       *累计支付总金额
       * </pre>
       *
       * <code>required int32 paySum = 2;</code>
       */
      public boolean hasPaySum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *累计支付总金额
       * </pre>
       *
       * <code>required int32 paySum = 2;</code>
       */
      public int getPaySum() {
        return paySum_;
      }
      /**
       * <pre>
       *累计支付总金额
       * </pre>
       *
       * <code>required int32 paySum = 2;</code>
       */
      public Builder setPaySum(int value) {
        bitField0_ |= 0x00000002;
        paySum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *累计支付总金额
       * </pre>
       *
       * <code>required int32 paySum = 2;</code>
       */
      public Builder clearPaySum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        paySum_ = 0;
        onChanged();
        return this;
      }

      private int onLinePaycCount_ ;
      /**
       * <pre>
       *线上累计支付次数
       * </pre>
       *
       * <code>required int32 onLinePaycCount = 3;</code>
       */
      public boolean hasOnLinePaycCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *线上累计支付次数
       * </pre>
       *
       * <code>required int32 onLinePaycCount = 3;</code>
       */
      public int getOnLinePaycCount() {
        return onLinePaycCount_;
      }
      /**
       * <pre>
       *线上累计支付次数
       * </pre>
       *
       * <code>required int32 onLinePaycCount = 3;</code>
       */
      public Builder setOnLinePaycCount(int value) {
        bitField0_ |= 0x00000004;
        onLinePaycCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *线上累计支付次数
       * </pre>
       *
       * <code>required int32 onLinePaycCount = 3;</code>
       */
      public Builder clearOnLinePaycCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        onLinePaycCount_ = 0;
        onChanged();
        return this;
      }

      private int onLinePaySum_ ;
      /**
       * <pre>
       *线上累计支付总金额
       * </pre>
       *
       * <code>required int32 onLinePaySum = 4;</code>
       */
      public boolean hasOnLinePaySum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *线上累计支付总金额
       * </pre>
       *
       * <code>required int32 onLinePaySum = 4;</code>
       */
      public int getOnLinePaySum() {
        return onLinePaySum_;
      }
      /**
       * <pre>
       *线上累计支付总金额
       * </pre>
       *
       * <code>required int32 onLinePaySum = 4;</code>
       */
      public Builder setOnLinePaySum(int value) {
        bitField0_ |= 0x00000008;
        onLinePaySum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *线上累计支付总金额
       * </pre>
       *
       * <code>required int32 onLinePaySum = 4;</code>
       */
      public Builder clearOnLinePaySum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        onLinePaySum_ = 0;
        onChanged();
        return this;
      }

      private int offLinePaycCount_ ;
      /**
       * <pre>
       *线下累计支付次数
       * </pre>
       *
       * <code>required int32 offLinePaycCount = 5;</code>
       */
      public boolean hasOffLinePaycCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *线下累计支付次数
       * </pre>
       *
       * <code>required int32 offLinePaycCount = 5;</code>
       */
      public int getOffLinePaycCount() {
        return offLinePaycCount_;
      }
      /**
       * <pre>
       *线下累计支付次数
       * </pre>
       *
       * <code>required int32 offLinePaycCount = 5;</code>
       */
      public Builder setOffLinePaycCount(int value) {
        bitField0_ |= 0x00000010;
        offLinePaycCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *线下累计支付次数
       * </pre>
       *
       * <code>required int32 offLinePaycCount = 5;</code>
       */
      public Builder clearOffLinePaycCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        offLinePaycCount_ = 0;
        onChanged();
        return this;
      }

      private int offLinePaySum_ ;
      /**
       * <pre>
       *线下累计支付总金额
       * </pre>
       *
       * <code>required int32 offLinePaySum = 6;</code>
       */
      public boolean hasOffLinePaySum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *线下累计支付总金额
       * </pre>
       *
       * <code>required int32 offLinePaySum = 6;</code>
       */
      public int getOffLinePaySum() {
        return offLinePaySum_;
      }
      /**
       * <pre>
       *线下累计支付总金额
       * </pre>
       *
       * <code>required int32 offLinePaySum = 6;</code>
       */
      public Builder setOffLinePaySum(int value) {
        bitField0_ |= 0x00000020;
        offLinePaySum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *线下累计支付总金额
       * </pre>
       *
       * <code>required int32 offLinePaySum = 6;</code>
       */
      public Builder clearOffLinePaySum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        offLinePaySum_ = 0;
        onChanged();
        return this;
      }

      private Object endTime_ = "";
      /**
       * <pre>
       *结算截止时间
       * </pre>
       *
       * <code>optional string endTime = 7;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *结算截止时间
       * </pre>
       *
       * <code>optional string endTime = 7;</code>
       */
      public String getEndTime() {
        Object ref = endTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            endTime_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *结算截止时间
       * </pre>
       *
       * <code>optional string endTime = 7;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *结算截止时间
       * </pre>
       *
       * <code>optional string endTime = 7;</code>
       */
      public Builder setEndTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结算截止时间
       * </pre>
       *
       * <code>optional string endTime = 7;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结算截止时间
       * </pre>
       *
       * <code>optional string endTime = 7;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        endTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:B114)
    }

    // @@protoc_insertion_point(class_scope:B114)
    private static final B114 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new B114();
    }

    public static B114 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<B114>
        PARSER = new com.google.protobuf.AbstractParser<B114>() {
      public B114 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new B114(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<B114> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<B114> getParserForType() {
      return PARSER;
    }

    public B114 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_A114_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_A114_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_B114_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_B114_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020BaseData14.proto\"/\n\004A114\022\021\n\tparkingId\030" +
      "\001 \002(\005\022\024\n\014clientSerial\030\002 \002(\t\"\231\001\n\004B114\022\020\n\010" +
      "payCount\030\001 \002(\005\022\016\n\006paySum\030\002 \002(\005\022\027\n\017onLine" +
      "PaycCount\030\003 \002(\005\022\024\n\014onLinePaySum\030\004 \002(\005\022\030\n" +
      "\020offLinePaycCount\030\005 \002(\005\022\025\n\roffLinePaySum" +
      "\030\006 \002(\005\022\017\n\007endTime\030\007 \001(\tB\'\n\031com.common.mo" +
      "del.protobufB\nBaseData14"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_A114_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_A114_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_A114_descriptor,
        new String[] { "ParkingId", "ClientSerial", });
    internal_static_B114_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_B114_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_B114_descriptor,
        new String[] { "PayCount", "PaySum", "OnLinePaycCount", "OnLinePaySum", "OffLinePaycCount", "OffLinePaySum", "EndTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
