// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.common.netty.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Head)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *通讯帧的包头
     * </pre>
     *
     * <code>required int32 flag = 1;</code>
     */
    boolean hasFlag();
    /**
     * <pre>
     *通讯帧的包头
     * </pre>
     *
     * <code>required int32 flag = 1;</code>
     */
    int getFlag();

    /**
     * <pre>
     *停车场id|token
     * </pre>
     *
     * <code>required string token = 2;</code>
     */
    boolean hasToken();
    /**
     * <pre>
     *停车场id|token
     * </pre>
     *
     * <code>required string token = 2;</code>
     */
    String getToken();
    /**
     * <pre>
     *停车场id|token
     * </pre>
     *
     * <code>required string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int32 msgId = 4;</code>
     */
    boolean hasMsgId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int32 msgId = 4;</code>
     */
    int getMsgId();

    /**
     * <pre>
     *校验码
     * </pre>
     *
     * <code>required string mac = 5;</code>
     */
    boolean hasMac();
    /**
     * <pre>
     *校验码
     * </pre>
     *
     * <code>required string mac = 5;</code>
     */
    String getMac();
    /**
     * <pre>
     *校验码
     * </pre>
     *
     * <code>required string mac = 5;</code>
     */
    com.google.protobuf.ByteString
        getMacBytes();

    /**
     * <code>required int32 status = 6;</code>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 6;</code>
     */
    int getStatus();

    /**
     * <pre>
     *请求数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 totalLen = 7;</code>
     */
    boolean hasTotalLen();
    /**
     * <pre>
     *请求数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 totalLen = 7;</code>
     */
    int getTotalLen();

    /**
     * <pre>
     *请求数据
     * </pre>
     *
     * <code>required bytes data = 8;</code>
     */
    boolean hasData();
    /**
     * <pre>
     *请求数据
     * </pre>
     *
     * <code>required bytes data = 8;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Head}
   */
  public  static final class Head extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Head)
      HeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Head() {
      flag_ = 0;
      token_ = "";
      msgId_ = 0;
      mac_ = "";
      status_ = 0;
      totalLen_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              flag_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              token_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              mac_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              status_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              totalLen_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_Head_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Head.class, Builder.class);
    }

    private int bitField0_;
    public static final int FLAG_FIELD_NUMBER = 1;
    private int flag_;
    /**
     * <pre>
     *通讯帧的包头
     * </pre>
     *
     * <code>required int32 flag = 1;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *通讯帧的包头
     * </pre>
     *
     * <code>required int32 flag = 1;</code>
     */
    public int getFlag() {
      return flag_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile Object token_;
    /**
     * <pre>
     *停车场id|token
     * </pre>
     *
     * <code>required string token = 2;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *停车场id|token
     * </pre>
     *
     * <code>required string token = 2;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *停车场id|token
     * </pre>
     *
     * <code>required string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private int msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int32 msgId = 4;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int32 msgId = 4;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int MAC_FIELD_NUMBER = 5;
    private volatile Object mac_;
    /**
     * <pre>
     *校验码
     * </pre>
     *
     * <code>required string mac = 5;</code>
     */
    public boolean hasMac() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *校验码
     * </pre>
     *
     * <code>required string mac = 5;</code>
     */
    public String getMac() {
      Object ref = mac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mac_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *校验码
     * </pre>
     *
     * <code>required string mac = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>required int32 status = 6;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 status = 6;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TOTALLEN_FIELD_NUMBER = 7;
    private int totalLen_;
    /**
     * <pre>
     *请求数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 totalLen = 7;</code>
     */
    public boolean hasTotalLen() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *请求数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 totalLen = 7;</code>
     */
    public int getTotalLen() {
      return totalLen_;
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *请求数据
     * </pre>
     *
     * <code>required bytes data = 8;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *请求数据
     * </pre>
     *
     * <code>required bytes data = 8;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalLen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mac_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, status_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, totalLen_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mac_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, status_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, totalLen_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Head)) {
        return super.equals(obj);
      }
      Head other = (Head) obj;

      boolean result = true;
      result = result && (hasFlag() == other.hasFlag());
      if (hasFlag()) {
        result = result && (getFlag()
            == other.getFlag());
      }
      result = result && (hasToken() == other.hasToken());
      if (hasToken()) {
        result = result && getToken()
            .equals(other.getToken());
      }
      result = result && (hasMsgId() == other.hasMsgId());
      if (hasMsgId()) {
        result = result && (getMsgId()
            == other.getMsgId());
      }
      result = result && (hasMac() == other.hasMac());
      if (hasMac()) {
        result = result && getMac()
            .equals(other.getMac());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && (getStatus()
            == other.getStatus());
      }
      result = result && (hasTotalLen() == other.hasTotalLen());
      if (hasTotalLen()) {
        result = result && (getTotalLen()
            == other.getTotalLen());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFlag()) {
        hash = (37 * hash) + FLAG_FIELD_NUMBER;
        hash = (53 * hash) + getFlag();
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasMsgId()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId();
      }
      if (hasMac()) {
        hash = (37 * hash) + MAC_FIELD_NUMBER;
        hash = (53 * hash) + getMac().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasTotalLen()) {
        hash = (37 * hash) + TOTALLEN_FIELD_NUMBER;
        hash = (53 * hash) + getTotalLen();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Head parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Head parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Head prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Head)
        HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_Head_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Head.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.Message.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mac_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        totalLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_Head_descriptor;
      }

      public Head getDefaultInstanceForType() {
        return Head.getDefaultInstance();
      }

      public Head build() {
        Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Head buildPartial() {
        Head result = new Head(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mac_ = mac_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.totalLen_ = totalLen_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Head) {
          return mergeFrom((Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Head other) {
        if (other == Head.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000002;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasMac()) {
          bitField0_ |= 0x00000008;
          mac_ = other.mac_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasTotalLen()) {
          setTotalLen(other.getTotalLen());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFlag()) {
          return false;
        }
        if (!hasToken()) {
          return false;
        }
        if (!hasMsgId()) {
          return false;
        }
        if (!hasMac()) {
          return false;
        }
        if (!hasStatus()) {
          return false;
        }
        if (!hasTotalLen()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Head) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int flag_ ;
      /**
       * <pre>
       *通讯帧的包头
       * </pre>
       *
       * <code>required int32 flag = 1;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *通讯帧的包头
       * </pre>
       *
       * <code>required int32 flag = 1;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <pre>
       *通讯帧的包头
       * </pre>
       *
       * <code>required int32 flag = 1;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *通讯帧的包头
       * </pre>
       *
       * <code>required int32 flag = 1;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = 0;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <pre>
       *停车场id|token
       * </pre>
       *
       * <code>required string token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *停车场id|token
       * </pre>
       *
       * <code>required string token = 2;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *停车场id|token
       * </pre>
       *
       * <code>required string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *停车场id|token
       * </pre>
       *
       * <code>required string token = 2;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车场id|token
       * </pre>
       *
       * <code>required string token = 2;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *停车场id|token
       * </pre>
       *
       * <code>required string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int32 msgId = 4;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int32 msgId = 4;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int32 msgId = 4;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int32 msgId = 4;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = 0;
        onChanged();
        return this;
      }

      private Object mac_ = "";
      /**
       * <pre>
       *校验码
       * </pre>
       *
       * <code>required string mac = 5;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *校验码
       * </pre>
       *
       * <code>required string mac = 5;</code>
       */
      public String getMac() {
        Object ref = mac_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mac_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *校验码
       * </pre>
       *
       * <code>required string mac = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        Object ref = mac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *校验码
       * </pre>
       *
       * <code>required string mac = 5;</code>
       */
      public Builder setMac(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *校验码
       * </pre>
       *
       * <code>required string mac = 5;</code>
       */
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *校验码
       * </pre>
       *
       * <code>required string mac = 5;</code>
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mac_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>required int32 status = 6;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 status = 6;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 6;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000010;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 6;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = 0;
        onChanged();
        return this;
      }

      private int totalLen_ ;
      /**
       * <pre>
       *请求数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 totalLen = 7;</code>
       */
      public boolean hasTotalLen() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *请求数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 totalLen = 7;</code>
       */
      public int getTotalLen() {
        return totalLen_;
      }
      /**
       * <pre>
       *请求数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 totalLen = 7;</code>
       */
      public Builder setTotalLen(int value) {
        bitField0_ |= 0x00000020;
        totalLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 totalLen = 7;</code>
       */
      public Builder clearTotalLen() {
        bitField0_ = (bitField0_ & ~0x00000020);
        totalLen_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>required bytes data = 8;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>required bytes data = 8;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>required bytes data = 8;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>required bytes data = 8;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Head)
    }

    // @@protoc_insertion_point(class_scope:Head)
    private static final Head DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Head();
    }

    public static Head getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Head>
        PARSER = new com.google.protobuf.AbstractParser<Head>() {
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Head(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Head> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    public Head getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Base)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *操作码
     * </pre>
     *
     * <code>required int32 op_code = 1;</code>
     */
    boolean hasOpCode();
    /**
     * <pre>
     *操作码
     * </pre>
     *
     * <code>required int32 op_code = 1;</code>
     */
    int getOpCode();

    /**
     * <pre>
     *版本号
     * </pre>
     *
     * <code>required int32 ver = 2;</code>
     */
    boolean hasVer();
    /**
     * <pre>
     *版本号
     * </pre>
     *
     * <code>required int32 ver = 2;</code>
     */
    int getVer();

    /**
     * <pre>
     *业务参数
     * </pre>
     *
     * <code>required int32 param = 3;</code>
     */
    boolean hasParam();
    /**
     * <pre>
     *业务参数
     * </pre>
     *
     * <code>required int32 param = 3;</code>
     */
    int getParam();

    /**
     * <pre>
     *业务数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 data_len = 4;</code>
     */
    boolean hasDataLen();
    /**
     * <pre>
     *业务数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 data_len = 4;</code>
     */
    int getDataLen();

    /**
     * <pre>
     *业务数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    boolean hasData();
    /**
     * <pre>
     *业务数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Base}
   */
  public  static final class Base extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Base)
      BaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Base.newBuilder() to construct.
    private Base(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Base() {
      opCode_ = 0;
      ver_ = 0;
      param_ = 0;
      dataLen_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Base(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              opCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ver_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              param_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              dataLen_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_Base_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_Base_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Base.class, Builder.class);
    }

    private int bitField0_;
    public static final int OP_CODE_FIELD_NUMBER = 1;
    private int opCode_;
    /**
     * <pre>
     *操作码
     * </pre>
     *
     * <code>required int32 op_code = 1;</code>
     */
    public boolean hasOpCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *操作码
     * </pre>
     *
     * <code>required int32 op_code = 1;</code>
     */
    public int getOpCode() {
      return opCode_;
    }

    public static final int VER_FIELD_NUMBER = 2;
    private int ver_;
    /**
     * <pre>
     *版本号
     * </pre>
     *
     * <code>required int32 ver = 2;</code>
     */
    public boolean hasVer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *版本号
     * </pre>
     *
     * <code>required int32 ver = 2;</code>
     */
    public int getVer() {
      return ver_;
    }

    public static final int PARAM_FIELD_NUMBER = 3;
    private int param_;
    /**
     * <pre>
     *业务参数
     * </pre>
     *
     * <code>required int32 param = 3;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *业务参数
     * </pre>
     *
     * <code>required int32 param = 3;</code>
     */
    public int getParam() {
      return param_;
    }

    public static final int DATA_LEN_FIELD_NUMBER = 4;
    private int dataLen_;
    /**
     * <pre>
     *业务数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 data_len = 4;</code>
     */
    public boolean hasDataLen() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *业务数据长度(DataLen)
     * </pre>
     *
     * <code>required int32 data_len = 4;</code>
     */
    public int getDataLen() {
      return dataLen_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *业务数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *业务数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOpCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataLen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, opCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ver_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, param_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, dataLen_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, opCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ver_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, param_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dataLen_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Base)) {
        return super.equals(obj);
      }
      Base other = (Base) obj;

      boolean result = true;
      result = result && (hasOpCode() == other.hasOpCode());
      if (hasOpCode()) {
        result = result && (getOpCode()
            == other.getOpCode());
      }
      result = result && (hasVer() == other.hasVer());
      if (hasVer()) {
        result = result && (getVer()
            == other.getVer());
      }
      result = result && (hasParam() == other.hasParam());
      if (hasParam()) {
        result = result && (getParam()
            == other.getParam());
      }
      result = result && (hasDataLen() == other.hasDataLen());
      if (hasDataLen()) {
        result = result && (getDataLen()
            == other.getDataLen());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOpCode()) {
        hash = (37 * hash) + OP_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getOpCode();
      }
      if (hasVer()) {
        hash = (37 * hash) + VER_FIELD_NUMBER;
        hash = (53 * hash) + getVer();
      }
      if (hasParam()) {
        hash = (37 * hash) + PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getParam();
      }
      if (hasDataLen()) {
        hash = (37 * hash) + DATA_LEN_FIELD_NUMBER;
        hash = (53 * hash) + getDataLen();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Base parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Base parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Base parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Base parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Base parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Base parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Base parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Base parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Base parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Base parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Base parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Base parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Base prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Base}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Base)
        BaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_Base_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_Base_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Base.class, Builder.class);
      }

      // Construct using com.common.model.protobuf.Message.Base.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        opCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ver_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        param_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        dataLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_Base_descriptor;
      }

      public Base getDefaultInstanceForType() {
        return Base.getDefaultInstance();
      }

      public Base build() {
        Base result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Base buildPartial() {
        Base result = new Base(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opCode_ = opCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ver_ = ver_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.param_ = param_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dataLen_ = dataLen_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Base) {
          return mergeFrom((Base)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Base other) {
        if (other == Base.getDefaultInstance()) return this;
        if (other.hasOpCode()) {
          setOpCode(other.getOpCode());
        }
        if (other.hasVer()) {
          setVer(other.getVer());
        }
        if (other.hasParam()) {
          setParam(other.getParam());
        }
        if (other.hasDataLen()) {
          setDataLen(other.getDataLen());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpCode()) {
          return false;
        }
        if (!hasVer()) {
          return false;
        }
        if (!hasParam()) {
          return false;
        }
        if (!hasDataLen()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Base parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Base) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int opCode_ ;
      /**
       * <pre>
       *操作码
       * </pre>
       *
       * <code>required int32 op_code = 1;</code>
       */
      public boolean hasOpCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *操作码
       * </pre>
       *
       * <code>required int32 op_code = 1;</code>
       */
      public int getOpCode() {
        return opCode_;
      }
      /**
       * <pre>
       *操作码
       * </pre>
       *
       * <code>required int32 op_code = 1;</code>
       */
      public Builder setOpCode(int value) {
        bitField0_ |= 0x00000001;
        opCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *操作码
       * </pre>
       *
       * <code>required int32 op_code = 1;</code>
       */
      public Builder clearOpCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opCode_ = 0;
        onChanged();
        return this;
      }

      private int ver_ ;
      /**
       * <pre>
       *版本号
       * </pre>
       *
       * <code>required int32 ver = 2;</code>
       */
      public boolean hasVer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *版本号
       * </pre>
       *
       * <code>required int32 ver = 2;</code>
       */
      public int getVer() {
        return ver_;
      }
      /**
       * <pre>
       *版本号
       * </pre>
       *
       * <code>required int32 ver = 2;</code>
       */
      public Builder setVer(int value) {
        bitField0_ |= 0x00000002;
        ver_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *版本号
       * </pre>
       *
       * <code>required int32 ver = 2;</code>
       */
      public Builder clearVer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ver_ = 0;
        onChanged();
        return this;
      }

      private int param_ ;
      /**
       * <pre>
       *业务参数
       * </pre>
       *
       * <code>required int32 param = 3;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *业务参数
       * </pre>
       *
       * <code>required int32 param = 3;</code>
       */
      public int getParam() {
        return param_;
      }
      /**
       * <pre>
       *业务参数
       * </pre>
       *
       * <code>required int32 param = 3;</code>
       */
      public Builder setParam(int value) {
        bitField0_ |= 0x00000004;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务参数
       * </pre>
       *
       * <code>required int32 param = 3;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000004);
        param_ = 0;
        onChanged();
        return this;
      }

      private int dataLen_ ;
      /**
       * <pre>
       *业务数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 data_len = 4;</code>
       */
      public boolean hasDataLen() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *业务数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 data_len = 4;</code>
       */
      public int getDataLen() {
        return dataLen_;
      }
      /**
       * <pre>
       *业务数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 data_len = 4;</code>
       */
      public Builder setDataLen(int value) {
        bitField0_ |= 0x00000008;
        dataLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务数据长度(DataLen)
       * </pre>
       *
       * <code>required int32 data_len = 4;</code>
       */
      public Builder clearDataLen() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dataLen_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *业务数据
       * </pre>
       *
       * <code>optional bytes data = 5;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *业务数据
       * </pre>
       *
       * <code>optional bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *业务数据
       * </pre>
       *
       * <code>optional bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务数据
       * </pre>
       *
       * <code>optional bytes data = 5;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Base)
    }

    // @@protoc_insertion_point(class_scope:Base)
    private static final Base DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Base();
    }

    public static Base getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Base>
        PARSER = new com.google.protobuf.AbstractParser<Base>() {
      public Base parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Base(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Base> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Base> getParserForType() {
      return PARSER;
    }

    public Base getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Head_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Head_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Base_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Base_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\"o\n\004Head\022\014\n\004flag\030\001 \002(\005\022\r\n" +
      "\005token\030\002 \002(\t\022\r\n\005msgId\030\004 \002(\005\022\013\n\003mac\030\005 \002(\t" +
      "\022\016\n\006status\030\006 \002(\005\022\020\n\010totalLen\030\007 \002(\005\022\014\n\004da" +
      "ta\030\010 \002(\014\"S\n\004Base\022\017\n\007op_code\030\001 \002(\005\022\013\n\003ver" +
      "\030\002 \002(\005\022\r\n\005param\030\003 \002(\005\022\020\n\010data_len\030\004 \002(\005\022" +
      "\014\n\004data\030\005 \001(\014B$\n\031com.common.model.protob" +
      "ufB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Head_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Head_descriptor,
        new String[] { "Flag", "Token", "MsgId", "Mac", "Status", "TotalLen", "Data", });
    internal_static_Base_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Base_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Base_descriptor,
        new String[] { "OpCode", "Ver", "Param", "DataLen", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
