spring:
    application:
        name: @project.artifactId@
    profiles:
        active: dev,native
    cloud:
        config:
            server:
                git:
                    # uri: https://git.oschina.net/eztcncom/server-config.git
                    # searchPaths: /
                    # username: dev@eztcn.com
                    # password: Ezt20170301
#                    uri: http://192.168.56.201:10080/vinesmario/spring-cloud-1.0.git
#                    searchPaths: /config-repo/{application}/{profile}
#                    username: vinesmario
#                    password: 12345678
                native:
                    search-locations: file:./config-repo

    rabbitmq:
        host: 192.168.56.202
        port: 5672
        username: guest
        password: guest

management:
    security:
        enabled: false